% MAIN launcher script, simulating GUI code

clc; close all;

% 1. This data is generated by gui or test launcher scripts:
dataParameters = struct('name',{},'path',{});

% 1.1 Create data object when user selects it:
dataObj1.name = 'A2';
dataObj1.path = 'src/test/testdata/A2_2015-10-30T15-14-12/';
dataParameters{1} = dataObj1;

dataObj2.name = 'A2';
dataObj2.path = 'src/test/testdata/A2_2015-10-30T15-14-12/';
dataParameters{2} = dataObj2;

% ... keep adding objects ...

% 2. Create models when user selects them:
modelParameters = struct( ...
    'tabu', struct('active',1,'initial',1,'phases',[1]), ...
    'LNS' , struct('active',0,'initial',1,'phases',[1]), ...
    'ampl', struct('active',0,'initial',1,'phases',[1]));

% 3. run launcher
status = mainlauncher(dataParameters, modelParameters);



% ---------------------------------------------
