function status = mainlauncher(dataParameters, modelParameters)
%MAINLAUNCHER Summary of this function goes here
%   Detailed explanation goes here



clc;
clear all;

% This funcion is in guitest
status = 1;

algorithmId=1;

while status ==1
    
    
    
    addpath(genpath('src/main/guitest'))
    [status, logPath] = CreateLog();
    [status, resultPath] = CreateResultStructure();
    rmpath(genpath('src/main/guitest'))

    % This data is generated by gui or test launcher scripts:
    dataParameters = struct('name',{},'path',{});
    
    dataObj1.name = 'A2'
    dataObj1.path = 'src/test/testdata/A2_2015-10-30T15-14-12/';
    data.Parameters{1} = dataObj1;
    
    modelParameters = struct( ...
        'tabu', struct('initial',1,'phases',[1]), ...
        'LNS' , struct('initial',1,'phases',[1]), ...
        'ampl', struct('initial',1,'phases',[1]));
    logfileParameters = struct('path',logPath,'id',algorithmId);
    resultParameters = struct('path',resultPath,'id',algorithmId);

    
    if 1
    % Add path for tabu main files:
    addpath(genpath('src/main/tabu')); %'src/main/tabu';
    status = tabumain(dataParameters,modelParameters.tabu,logfileParameters,resultParameters);
    rmpath(genpath('src/main/tabu')); % 'src/main/tabu';
    % -----------------------------
    
    
    else
        addpath(genpath('src/main/ampl'));
        runstatus = amplmain(dataParameters,modelParameters{1},logParameters,resultParameters)
        rmpath(genpath('src/main/ampl'));
        
    end
    
    status = 2;
    algorithmId = algorithmId +1;
end






end

