clc;
clear all;

% This funcion is in guitest
status = 1;

algorithmId=1;

while status ==1
    addpath(genpath('src/main/guitest'))
    [status, logPath] = CreateLog();
    [status, resultPath] = CreateResultStructure();
    rmpath(genpath('src/main/guitest'))

    % This data is generated by gui or test launcher scripts:
    dataParameters = struct('path','src/test/testdata/A2_2015-10-30T15-14-12/');
    modelParameters = struct( ...
        'tabu', struct('initial',1,'phases',[1]), ...
        'LNS' , struct('initial',1,'phases',[1]), ...
        'ampl', struct('initial',1,'phases',[1]));
    logfileParameters = struct('path',logPath,'id',algorithmId);
    resultParameters = struct('path',resultPath,'id',algorithmId);

    % Add path for tabu main files:
    addpath(genpath('src/main/tabu')); %'src/main/tabu';
    status = tabumain(dataParameters,modelParameters.tabu,logfileParameters,resultParameters);
    rmpath(genpath('src/main/tabu')); % 'src/main/tabu';
    % -----------------------------
    
    status = 2;
    algorithmId = algorithmId +1;
end

